# Generated by Django 5.2.1 on 2025-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='loc',
            field=models.CharField(max_length=30),
        ),
    ]
